### ISSUE TITLE
Serving static files: How to do directory listing/index?

### ISSUE THREAD

**Issue by stefandesu** [gbv/coli-conc-server#8]
For some things, we need to have a HTTP server for static files with directory listing enabled. busybox (which I've planned on using for static files) does not support this out of the box, and I wasn't able to figure out how to use their `httpd_indexcgi.c` script to enable this.

Low priority, but required to replace https://coli-conc.gbv.de/rvk/data/.

**Comment by nichtich** [comment]
Maybe nginx with fancyindex module?

**Comment by stefandesu** [comment]
That would work. I think I was looking for a very small solution, but I guess a few more MB don't make a big difference.

**Comment by nichtich** [comment]
I also use nginx with https://github.com/Naereen/Nginx-Fancyindex-Theme - this is very useful becasue `README.md` is shown as well.

**Comment by stefandesu** [comment]
That looks great! I'll look into getting this to work inside a Docker container.

**Comment by stefandesu** [comment]
I added the theme as a separate service (because it needs to be available at a subpath for all other services that use it) and it also serves as its own example: https://coli-conc.gbv.de/Nginx-Fancyindex-Theme-light/
